dataMin = '2014-01-01'
dataMax = '2015-09-30'
pnaPowiaty = polacz_pna_powiaty(przygotuj_pna(), przygotuj_powiaty(), dataMin, dataMax) # t1
jednostki = przygotuj_jednostki() # t2
# zus = przygotuj_zus(dataMin, dataMax) # t3
# save(zus, file = 'cache/ZUS.RData', compress = TRUE)
load('cache/ZUS.RData')
# utrataEtatu = przygotuj_utrata_pracy(zus, dataMax) # t4
# save(utrataEtatu, file = 'cache/utrataEtatu.RData', compress = TRUE)
load('cache/utrataEtatu.RData')
zdau = przygotuj_zdau() # t5
baza = polacz_zus_zdau(zus, zdau, pnaPowiaty) # t6

studyp = oblicz_studyp(zdau) # t7

okienkoMin = 0
okienkoMax = 1000
okienko = oblicz_okienko(baza, okienkoMin, okienkoMax, dataMin, dataMax) # t8
# save(okienko, file = 'cache/okienko.RData', compress = TRUE)
# load('cache/okienko.RData')

czas = oblicz_zmienne_czasowe(okienko, utrataEtatu) # t9
abs1 = oblicz_absolwent(okienko) # t10
abs2 = oblicz_absolwent_okres(okienko) # t11
nnn  = oblicz_nowi_pracodawcy(okienko) # t12
nmle = oblicz_utrata_etatu(okienko, utrataEtatu) # t13
zam  = oblicz_zamieszkanie(okienko, jednostki, okienkoMin) # t14
razem = abs1 %>% # t15
  full_join(abs2) %>%
  full_join(nnn) %>%
  full_join(nmle) %>%
  full_join(zam) %>%
  full_join(czas) %>%
  left_join(oblicz_okienko(zdau, okienkoMin, okienkoMax, dataMin, dataMax)) # left_join, bo zdau zawiera też nieabsolwentów
#rm(abs1, abs2, nnn, nmle, zam, czas)
razem = oblicz_zmienne_pochodne(razem) # t16
save(razem, file = 'cache/razem.RData', compress = TRUE)
