#' oblicza zmienne wywodzone z już wcześniej policzonych
#' @param dane ramki danych wygenerowane wewnątrz pomocą funkcji
#'   \code{\link{agreguj_do_miesiecy}} lub \code{\link{agreguj_do_okresu}}
#' @param multidplyr czy obliczać na wielu rdzeniach korzystając z pakietu
#'   multidplyr
#' @return data.frame wyliczone zmienne
#' @import dplyr
oblicz_zmienne_pochodne = function(dane, multidplyr = TRUE){
  if (multidplyr) {
    dane = multidplyr::partition(dane, id_zdau)
  }

  dane = dane %>%
    mutate_(
      nm_bd  = ~dplyr::coalesce(nm_bd_n, 0L) + dplyr::coalesce(nm_bd_s, 0L),
      nm_d   = ~dplyr::coalesce(nm_d_n, 0L) + dplyr::coalesce(nm_d_s, 0L),
      nm_e   = ~dplyr::coalesce(nm_e_n, 0L) + dplyr::coalesce(nm_e_s, 0L),
      nm_i   = ~dplyr::coalesce(nm_i_n, 0L) + dplyr::coalesce(nm_i_s, 0L),
      nm_ii  = ~dplyr::coalesce(nm_ii_n, 0L) + dplyr::coalesce(nm_ii_s, 0L),
      nm_j   = ~dplyr::coalesce(nm_j_n, 0L) + dplyr::coalesce(nm_j_s, 0L),
      nm_m   = ~dplyr::coalesce(nm_m_n, 0L) + dplyr::coalesce(nm_m_s, 0L),
      nm_n   = ~dplyr::coalesce(nm_n_n, 0L) + dplyr::coalesce(nm_n_s, 0L),
      nm_p   = ~dplyr::coalesce(nm_p_n, 0L) + dplyr::coalesce(nm_p_s, 0L),
      nm_pnd = ~dplyr::coalesce(nm_pnd_n, 0L) + dplyr::coalesce(nm_pnd_s, 0L),
      nm_s   = ~dplyr::coalesce(nm_s_n, 0L) + dplyr::coalesce(nm_s_s, 0L),
      nm_z   = ~dplyr::coalesce(nm_z_n, 0L) + dplyr::coalesce(nm_z_s, 0L),
      if_b   = ~as.integer(nm_b > 0L),
      if_b2  = ~as.integer(nm_b2 > 0L),
      if_d   = ~as.integer(nm_d > 0L),
      if_d_n = ~as.integer(nm_d_n > 0L),
      if_d_s = ~as.integer(nm_d_s > 0L),
      if_e   = ~as.integer(nm_e > 0L),
      if_e_n = ~as.integer(nm_e_n > 0L),
      if_e_s = ~as.integer(nm_e_s > 0L),
      if_end = ~as.integer(nm_end > 0L),
      if_i = ~as.integer(nm_i > 0L),
      if_ii = ~as.integer(nm_ii > 0L),
      if_m   = ~as.integer(nm_m > 0L),
      if_n   = ~as.integer(nm_n > 0L),
      if_nnd = ~as.integer(nm_nnd > 0L),
      if_p   = ~as.integer(nm_p > 0L),
      if_p_n = ~as.integer(nm_p_n > 0L),
      if_p_s = ~as.integer(nm_p_s > 0L),
      if_pnd = ~as.integer(nm_pnd > 0L),
      if_pnd_n = ~as.integer(nm_pnd_n > 0L),
      if_pnd_s = ~as.integer(nm_pnd_s > 0L),
      if_s   = ~as.integer(nm_s > 0L),
      if_s_n = ~as.integer(nm_s_n > 0L),
      if_s_s = ~as.integer(nm_s_s > 0L),
      if_snd = ~as.integer(nm_snd > 0L),
      if_x_s = ~as.integer(nm_x_s > 0L),
      if_x_n = ~as.integer(nm_x_n > 0L),
      epm_e   = ~dplyr::coalesce(npm_e / nm_e, NA_real_),
      epm_e_n = ~dplyr::coalesce(npm_e_n / nm_e_n, NA_real_),
      epm_e_s = ~dplyr::coalesce(npm_e_s / nm_e_s, NA_real_),
      pm_b    = ~dplyr::coalesce(100L * nm_b / len, NA_real_),
      pm_b2   = ~dplyr::coalesce(100L * nm_b2 / len, NA_real_),
      pm_b_n  = ~dplyr::coalesce(100L * nm_b / nm_x_n, NA_real_),
      pm_bd   = ~dplyr::coalesce(100L * nm_bd / len, NA_real_),
      pm_bd_n = ~dplyr::coalesce(100L * nm_bd_n / nm_x_n, NA_real_),
      pm_bd_s = ~dplyr::coalesce(100L * nm_bd_s / nm_x_s, NA_real_),
      pm_be   = ~dplyr::coalesce((len - nm_e) / len, NA_real_),
      pm_bp   = ~dplyr::coalesce((len - nm_p) / len, NA_real_),
      pm_d    = ~dplyr::coalesce(100L * nm_d / len, NA_real_),
      pm_d_n  = ~dplyr::coalesce(100L * nm_d_n / nm_x_n, NA_real_),
      pm_d_s  = ~dplyr::coalesce(100L * nm_d_s / nm_x_s, NA_real_),
      pm_e    = ~dplyr::coalesce(100L * nm_e / len, NA_real_),
      pm_e_n  = ~dplyr::coalesce(100L * nm_e_n / nm_x_n, NA_real_),
      pm_e_s  = ~dplyr::coalesce(100L * nm_e_s / nm_x_s, NA_real_),
      pm_end  = ~dplyr::coalesce(100L * nm_end / len, NA_real_),
      pm_i    = ~dplyr::coalesce(100L * nm_i / len, NA_real_),
      pm_i_n  = ~dplyr::coalesce(100L * nm_i_n / nm_x_n, NA_real_),
      pm_i_s  = ~dplyr::coalesce(100L * nm_i_s / nm_x_s, NA_real_),
      pm_ii   = ~dplyr::coalesce(100L * nm_ii / len, NA_real_),
      pm_ii_n = ~dplyr::coalesce(100L * nm_ii_n / nm_x_n, NA_real_),
      pm_ii_s = ~dplyr::coalesce(100L * nm_ii_s / nm_x_s, NA_real_),
      pm_n    = ~dplyr::coalesce(100L * nm_n / len, NA_real_),
      pm_n_n  = ~dplyr::coalesce(100L * nm_n_n / nm_x_n, NA_real_),
      pm_n_s  = ~dplyr::coalesce(100L * nm_n_s / nm_x_s, NA_real_),
      pm_nnd  = ~dplyr::coalesce(100L * nm_nnd / len, NA_real_),
      pm_p    = ~dplyr::coalesce(100L * nm_p / len, NA_real_),
      pm_p_n  = ~dplyr::coalesce(100L * nm_p_n / nm_x_n, NA_real_),
      pm_p_s  = ~dplyr::coalesce(100L * nm_p_s / nm_x_s, NA_real_),
      pm_pnd  = ~dplyr::coalesce(100L * nm_pnd / len, NA_real_),
      pm_pnd_n = ~dplyr::coalesce(100L * nm_pnd_n / nm_x_n, NA_real_),
      pm_pnd_s = ~dplyr::coalesce(100L * nm_pnd_s / nm_x_s, NA_real_),
      pm_s    = ~dplyr::coalesce(100L * nm_s / len, NA_real_),
      pm_s_n  = ~dplyr::coalesce(100L * nm_s_n / nm_x_n, NA_real_),
      pm_s_s  = ~dplyr::coalesce(100L * nm_s_s / nm_x_s, NA_real_),
      pm_snd  = ~dplyr::coalesce(100L * nm_snd / len, NA_real_),
      pm_x_n  = ~dplyr::coalesce(100L * nm_x_n / len, NA_real_),
      pm_x_s  = ~dplyr::coalesce(100L * nm_x_s / len, NA_real_),
      sz_e = ~dplyr::coalesce(sz_e_n, 0) + dplyr::coalesce(sz_e_s, 0),
      sz_n = ~dplyr::coalesce(sz_n_n, 0) + dplyr::coalesce(sz_n_s, 0),
      sz_p = ~dplyr::coalesce(sz_p_n, 0) + dplyr::coalesce(sz_p_s, 0),
      sz_s = ~dplyr::coalesce(sz_s_n, 0) + dplyr::coalesce(sz_s_s, 0),
      sz_x = ~dplyr::coalesce(sz_x_n, 0) + dplyr::coalesce(sz_x_s, 0),
      sz_z = ~dplyr::coalesce(sz_z_n, 0) + dplyr::coalesce(sz_z_s, 0),
      ez_e   = ~dplyr::coalesce(sz_e / nm_e, NA_real_),
      ez_e_n = ~dplyr::coalesce(sz_e_n / nm_e_n, NA_real_),
      ez_e_s = ~dplyr::coalesce(sz_e_s / nm_e_s, NA_real_),
      ez_x   = ~dplyr::coalesce(sz_x / len, NA_real_),
      ez_z   = ~dplyr::coalesce(sz_z / nm_z, NA_real_),
      ez_z_n = ~dplyr::coalesce(sz_z_n / nm_z_n, NA_real_),
      ez_z_s = ~dplyr::coalesce(sz_z_s / nm_z_s, NA_real_),
      wzg_ez_e     = ~dplyr::coalesce(ez_e / ezpow_e, NA_real_),
      wzg_ez_e_n   = ~dplyr::coalesce(ez_e_n / ezpow_e_n, NA_real_),
      wzg_ez_e_s   = ~dplyr::coalesce(ez_e_s / ezpow_e_s, NA_real_),
      wzg_ez_z     = ~dplyr::coalesce(ez_z / ezpow_z, NA_real_),
      wzg_ez_z_n   = ~dplyr::coalesce(ez_z_n / ezpow_n, NA_real_),
      wzg_ez_z_s   = ~dplyr::coalesce(ez_z_s / ezpow_s, NA_real_),
      wzg_ryzbez   = ~dplyr::coalesce(pm_b / ppow_b, 0),
      wzg_ryzbez_n = ~dplyr::coalesce(pm_b_n / ppow_b_n, 0),
      status = ~if_end + if_nnd*2 + if_snd*4 + if_d*8 + if_b*16 + if_i*32 + if_x_s*64
    ) %>%
    collect() %>%
    ungroup()
  return(dane)
}
